steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/helloimage', '.' ]
  
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: 
    - -c
    - echo $$msg
  secretEnv: ['msg']

availableSecrets:
   secretManager:
   - versionName: projects/$PROJECT_ID/secrets/Secret1/versions/latest
     env: 'msg'

images:
- 'gcr.io/$PROJECT_ID/helloimage'
